deepspeed --include localhost:5,6 \
    --master_port=9907 src/train_bash.py \
    --deepspeed ds_config.json \
    --stage sft \
    --model_name_or_path /mnt/nas_data/zyj_workspace/zyj_data/Baichuan2-13B-Chat \
    --output_dir /mnt/nas_data/zyj_workspace/zyj_data/sft_output/bachuan2-13B-sft-etc-v5-50e-bs16-codev0.5.0\
    --do_train \
    --dataset  etc-v5-700-total-output\
    --split train \
    --val_size 0.1 \
    --template baichuan2 \
    --finetuning_type lora \
    --lora_rank 8 \
    --lora_target W_pack \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --preprocessing_num_workers 16 \
    --lr_scheduler_type cosine \
    --logging_steps 5 \
    --save_steps 100 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --num_train_epochs 50 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --fp16 \
    --overwrite_output_dir True 
