deepspeed --include localhost:0 \
    --master_port=9903 src/train_bash.py \
    --deepspeed /mnt/nas_data/zyj_workspace/zyj_code/LLaMA-Efficient-Tuning/examples/deepspeed/ds_z3_config.json \
    --stage sft \
    --model_name_or_path /mnt/nas_data2/zyj_workspace/zyj_data/LLM/QWEN/Qwen1.5-14B-Chat \
    --output_dir /mnt/nas_data2/zyj_workspace/zyj_data/sft-output/agent_test \
    --do_train \
    --dataset  agent_instruct_local\
    --split train \
    --val_size 0.1 \
    --template qwen \
    --finetuning_type lora \
    --lora_rank 8 \
    --lora_target q_proj,v_proj \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --preprocessing_num_workers 16 \
    --lr_scheduler_type cosine \
    --logging_steps 50 \
    --save_steps 100 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.5 \
    --num_train_epochs 12 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --fp16 \
    --overwrite_output_dir True 
